# Generated by Django 4.1.3 on 2023-03-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttranslation',
            name='content',
            field=models.TextField(verbose_name='Maqola'),
        ),
    ]
